[package]
name = "gitea"
version = "0.1.0"
authors = ["Russell Sim <russell.sim@gmail.com>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
async-trait = "0.1"
bytes = "0.5"
failure = "0.1"
futures = "0.3"
http = "0.2"
lazy_static = "1.4"
log = "0.4"
mime = { git = "https://github.com/hyperium/mime" }
mime_guess = "2.0"
parking_lot = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
tokio-util = { version = "0.3", features = ["codec"] }
url = "2.1"

tokio = { version = "0.2", features = ["fs", "io-util"] }
reqwest = { version = "0.10", features = ["stream", "json"] }

[workspace]
